tiles:
sprite0:                              ;Air
.db $00,$00,$00,$00,$00,$00,$00,$00
.db $00,$00,$00,$00,$00,$00,$00,$00
.db $00,$00,$00,$00,$00,$00,$00,$00
.db $00,$00,$00,$00,$00,$00,$00,$00
sprite1:                              ;Construction small
.db $55,$60,$18,$06,$01,$09,$24,$90
.db $55,$09,$24,$90,$40,$60,$18,$06
.db $6A,$55,$00,$00,$00,$00,$00,$00
.db $A9,$55,$00,$00,$00,$00,$00,$00
sprite2:                              ;Construction big
.db $55,$6A,$90,$10,$24,$04,$09,$01
.db $55,$A9,$06,$04,$18,$10,$60,$40
.db $01,$01,$06,$04,$18,$10,$60,$40
.db $40,$40,$90,$10,$24,$04,$09,$01
sprite3:                              ;Ladder
.db $C0,$C0,$EA,$FF,$C0,$C0,$EA,$FF
.db $03,$03,$AB,$FF,$03,$03,$AB,$FF
.db $C0,$C0,$EA,$FF,$C0,$C0,$EA,$FF
.db $03,$03,$AB,$FF,$03,$03,$AB,$FF
sprite4:                              ;Conveyor right left
.db $55,$7F,$7F,$7F,$7F,$6A,$7F,$7F
.db $55,$BF,$EF,$FB,$FE,$AA,$FE,$FB
.db $7F,$7F,$55,$00,$00,$00,$00,$00
.db $EF,$BF,$55,$00,$00,$00,$00,$00
sprite5:                              ;Conveyor right middle
.db $55,$FF,$FF,$FF,$FF,$AA,$FF,$FF
.db $55,$BF,$EF,$FB,$FE,$AA,$FE,$FB
.db $FF,$FF,$55,$00,$00,$00,$00,$00
.db $EF,$BF,$55,$00,$00,$00,$00,$00
sprite6:                              ;Conveyor right right
.db $55,$FE,$FF,$FF,$FF,$AA,$FF,$FF
.db $55,$FD,$BD,$ED,$F9,$A9,$F9,$ED
.db $FF,$FE,$55,$00,$00,$00,$00,$00
.db $BD,$FD,$55,$00,$00,$00,$00,$00
sprite7:                              ;Conveyor left left
.db $55,$7F,$7E,$7B,$6F,$6A,$6F,$7B
.db $55,$BF,$FF,$FF,$FF,$AA,$FF,$FF
.db $7E,$7F,$55,$00,$00,$00,$00,$00
.db $FF,$BF,$55,$00,$00,$00,$00,$00
sprite8:                              ;Conveyor left middle
.db $55,$FE,$FB,$EF,$BF,$AA,$BF,$EF
.db $55,$FF,$FF,$FF,$FF,$AA,$FF,$FF
.db $FB,$FE,$55,$00,$00,$00,$00,$00
.db $FF,$FF,$55,$00,$00,$00,$00,$00
sprite9:                              ;Conveyor left right
.db $55,$FE,$FB,$EF,$BF,$AA,$BF,$EF
.db $55,$FD,$FD,$FD,$FD,$A9,$FD,$FD
.db $FB,$FE,$55,$00,$00,$00,$00,$00
.db $FD,$FD,$55,$00,$00,$00,$00,$00
sprite10:                            ;Lunch
.db $00,$00,$00,$00,$00,$00,$00,$00
.db $00,$00,$00,$00,$00,$00,$00,$00
.db $00,$05,$05,$05,$05,$05,$05,$05
.db $00,$50,$7C,$5C,$5C,$5C,$7C,$50
